import math

#screen settings
RESOLUTION = WIDTH, HEIGHT = 2560, 1440
FPS = 60

#3D projection settings
DEFINITION = 4
MAX_DEPTH = 30

#lighting settings
DARKNESS_MULTIPLIER = 0.1
INVERSE_DARKNESS_MULTIPLIER = 1 / DARKNESS_MULTIPLIER
MAX_LIGHT_DISTANCE = 15
INVERSE_MAX_LIGHT_DISTANCE = 1 / MAX_LIGHT_DISTANCE
MAX_FLASHLIGHT_SCREEN_DISTANCE = ((HEIGHT // 2) * 0.9)**2
INVERSE_MAX_FLASHLIGHT_SCREEN_DISTANCE = 1 / MAX_FLASHLIGHT_SCREEN_DISTANCE
FLASHLIGHT_DISTANCE_NEGATION = 0
INVERSE_FLASHLIGHT_DISTANCE_NEGATION = 1 / ((1 - FLASHLIGHT_DISTANCE_NEGATION) + 0.00001)