import math

#screen settings
RESOLUTION = WIDTH, HEIGHT = 1500, 900
FPS = 60

#3D projection settings
FOV = math.pi / 3
RAY_AMT = WIDTH // 12
LIGHT_SEG_SIZE = 12
RAY_DELTA_ANGLE = FOV / RAY_AMT
MAX_DEPTH = 30
RAY_WIDTH_SCALE = WIDTH // RAY_AMT
SCREEN_DISTANCE = (WIDTH // 2) / math.tan(FOV / 2)
SCREEN_CENTER = (WIDTH //2, HEIGHT // 2)

#lighting settings
DARKNESS_MULTIPLIER = 0.5
INVERSE_DARKNESS_MULTIPLIER = 1 / DARKNESS_MULTIPLIER
MAX_LIGHT_DISTANCE = 15
INVERSE_MAX_LIGHT_DISTANCE = 1 / MAX_LIGHT_DISTANCE
MAX_FLASHLIGHT_SCREEN_DISTANCE = ((HEIGHT // 2) * 0.9)**2
INVERSE_MAX_FLASHLIGHT_SCREEN_DISTANCE = 1 / MAX_FLASHLIGHT_SCREEN_DISTANCE
FLASHLIGHT_DISTANCE_NEGATION = 0
INVERSE_FLASHLIGHT_DISTANCE_NEGATION = 1 / ((1 - FLASHLIGHT_DISTANCE_NEGATION) + 0.00001)